### ISSUE TITLE
Add role=transcription for hOCR files

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/google-books#197]
@jcoyne commented on [Wed Jan 08 2020](https://github.com/sul-dlss/sdr-api/issues/45)

in the contentMetadata.

---

@jcoyne commented on [Wed Jan 22 2020](https://github.com/sul-dlss/sdr-api/issues/45#issuecomment-577400754)

@jermnelson you will find that this is something we can add to the API after https://github.com/sul-dlss/sdr-api/pull/96 is merged. The `use` field would be what we'd use. https://github.com/sul-dlss/cocina-models/blob/master/docs/maps/File.json#L83

**Comment by mjgiarlo** [comment]
# Q&A

* How do we know if a file is an hOCR file?
  * Provisional answer: if it's an HTML file, we assume it's the OCR file.
* Does sdr-client already know how to deal with `role=transcription` in files metadata?
  * No.
* Where is use information persisted in sdr-api?
  * In ActiveStorage::Blob instance metadata? Where else? There may be work to do here, or maybe not.

# TO-DO

## google-books

- [ ] Add `Use` file metadata operation to `app/services/` that determines whether a file is an OCR file and, if so, flags it in files metadata as a transcription. Requirements:
  - [ ] Define `NAME` constant
  - [ ] Define `self.for(file:)` method
- [ ] Wire `Use` operation into `FileMetadataBuilder`
- [ ] Ensure `Use` operation is working as expected in `sdr_importer_spec.rb` (as a sort of integration test

## sdr-client

- [ ] Make sure `SdrClient::Deposit::File` in `sdr-client` knows how to deal with use metadata (e.g., set a `@use` attr and deal with it like other instance variables are being passed around): https://github.com/sul-dlss/sdr-client/blob/master/lib/sdr_client/deposit/file.rb
  - [ ] In `#as_json`, include `use` hash (subkeys are `description` and `type`)
    - [ ] Figure out what `description` and `type` should look like

## sdr-api

- [ ] In `ContentMetadataGenerator#create_file_node`, reach into cocina file and fetch the `type` attr of the `use` attr and set it as the `role` on the file node (value should be `transcription`).

**Comment by mjgiarlo** [comment]
We believe this issue is now done, and @jermnelson will close once we've done some integration testing.

**Comment by jermnelson** [comment]
This looks like it done. For example, checking Argo for [druid:mf999fv2483](https://argo-stage.stanford.edu/view/druid:mf999fv2483) show that contentMetadata role being set correctly.
